export const Types = {
  ORDERS: {
    LIST: {
      REQUEST: 'ORDERS.LIST.REQUEST',
      RECEIVE: 'ORDERS.LIST.RECEIVE',
      ERROR: 'ORDERS.LIST.RECEIVE',
    },
    UPDATE_STATUS: {
      REQUEST: 'ORDERS.UPDATE_STATUS.REQUEST',
      RECEIVE: 'ORDERS.UPDATE_STATUS.RECEIVE',
      ERROR: 'ORDERS.UPDATE_STATUS.ERROR',
    },
    USER: {
      LIST: {
        REQUEST: 'ORDERS.USER.LIST.REQUEST',
        RECEIVE: 'ORDERS.USER.LIST.RECEIVE',
        ERROR: 'ORDERS.USER.LIST.ERROR',
      },
      UPDATE_STATUS: {
        REQUEST: 'ORDERS.USER.UPDATE_STATUS.REQUEST',
        RECEIVE: 'ORDERS.USER.UPDATE_STATUS.RECEIVE',
        ERROR: 'ORDERS.USER.UPDATE_STATUS.ERROR',
      },
    },
    ITEM: {
      ADD: {
        REQUEST: 'ORDERS.ITEM.ADD.REQUEST',
        RECEIVE: 'ORDERS.ITEM.ADD.RECEIVE',
        ERROR: 'ORDERS.ITEM.ADD.ERROR',
      },
      REMOVE: {
        REQUEST: 'ORDERS.ITEM.REMOVE.REQUEST',
        RECEIVE: 'ORDERS.ITEM.REMOVE.RECEIVE',
        ERROR: 'ORDERS.ITEM.REMOVE.ERROR',
      },
      UPDATE_QUANTITY: {
        REQUEST: 'ORDERS.ITEM.UPDATE_QUANTITY.REQUEST',
        RECEIVE: 'ORDERS.ITEM.UPDATE_QUANTITY.RECEIVE',
        ERROR: 'ORDERS.ITEM.UPDATE_QUANTITY.ERROR',
      },
    },
  },
} as const;

export const DATA_KEY = 'orders';
export const DATA_KEY_ITEM = 'books';
